version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3307:3306'
    expose:
      - 3306
    environment:
      - DATABASE_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=Duyngo123@
      - MYSQL_DATABASE=my2
  backend:
    build:
      context: ../../BE
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
