version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "3307:3307"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Duyngo123@
      - POSTGRES_DB=my2
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "cindyrid1305@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - postgres
